### PR TITLE
Copied over ansible folder and Vagrantfile from dev-standards project.

### PR DESCRIPTION
**Pull request by philbarbato**
`vagrant up` fails in the website starter project unless you use these files.

### CODE REVIEW

**Comment by kellypacker** [comment]
@philbarbato does it fail because the submodule is not added? Did you run `make create`? I've tried to encapsulate the adding of the submodule into that easier command, but I've had to change it a couple times. It's been awhile, so I'm not sure if that command is correct. That adds the submodule and runs `vagrant up`.

**Comment by philbarbato** [comment]
@kellypacker It's not because the submodule is not added. It fails even after I add the submodule. I did not run `make create` though. I added the submodule and ran `vagrant up` manually.  I think it's failing because this project has an older version of Vagrant than the submodule is configured for.

**Comment by likeuntomurphy** [comment]
What is the error you saw?

**Comment by kellypacker** [comment]
On master I destroyed my local box and tried to run `make create` and it said `ansible/roles' already exists in the index`. So I ran `git submodule update --init ansible/roles` and that worked. 

I destroyed the box again, recloned and switched to this branch. I was able to run `make create` and it worked. So that is good. 

One thing I noticed is that the `ansible/group_vars/all` now sets the hostname to `example.test` (rather than specific to this repo `fm-website-starter.dev`). The idea with this repo is that is would be a place to grab files and copy them into a new dir and setup the provisioner for the new site. It would be more convenient to clone this repo and work with it directly for a new site, but certain things would have to be done, like remove the git remote for this repo. Also I'm not sure of the implications of having a box and then changing the host, etc. Maybe it would have to be initially destroyed? Maybe not. So maybe we could move it to become more generic and reusable. But that seems like a separate issue. We'd have to update the readme, etc.

**Comment by kellypacker** [comment]
Closing because the Rokanan setup was added to the repo.

**Pull request closed without merging**
